language: generic

matrix:
    include:
        - os: linux
          env: RUN_LINT=true
        - os: osx
          env: RUN_LINT=false

install:
    - git fetch --unshallow
    - git clone --depth 1 --single-branch https://github.com/thinca/vim-themis && (cd vim-themis && git rev-parse HEAD)
    - |
      if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
        tar xzf nvim-macos.tar.gz
      else
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
        tar xzf nvim-linux64.tar.gz
      fi
    - export PATH=$(pwd)/nvim-${TRAVIS_OS_NAME}64/bin:$PATH
    - |
      if [[ "$RUN_LINT" == "true" ]]; then
        pip3 install --user vim-vint
      fi

before_script:
    - uname -a
    - nvim --version

script:
    - THEMIS_VIM=nvim ./vim-themis/bin/themis ./test
    - |
      if [[ "$RUN_LINT" == "true" ]]; then
        vint .
      fi
